sudo: required
services:
  - docker

before_install:
  - docker build -t samirpatelgx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samirpatelgx/react-test npm test -- --coverage

after_success:
  - docker build -t samirpatelgx/multi-client ./client
  - docker build -t samirpatelgx/multi-nginx ./nginx
  - docker build -t samirpatelgx/multi-server ./server
  - docker build -t samirpatelgx/multi-worker ./worker
  # Take those images and push them to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push samirpatelgx/multi-client
  - docker push samirpatelgx/multi-nginx
  - docker push samirpatelgx/multi-server
  - docker push samirpatelgx/multi-worker
  


